### ISSUE TITLE
Vatsim auth token endpoint: User not found

### ISSUE THREAD

**Issue by Reisen-Wandern-Tauchen** [renorris/openfsd#2]
I keep running into issues with user authentification with openfsd.

### How to reproduce:
- compile openfsd on Debian Bullseye
- start opfenfsd with `FSD_ADDR=0.0.0.0:6810 HTTPS_ENABLED=true DATABASE_FILE=./fsd.db MOTD=openFSD TLS_CERT_FILE=/path/to/cert/file.crt TLS_KEY_FILE=/path/to/cert/file.key ./fsd`
- set up my user database (no vatsim-users!)
- run swift version 0.14.142 (currently most recent version)
- set up swift to connect with openfsd configured with Eco. `VATSIM` and Type `FSD [VATSIM]` and server address and port accordingly
- try to connect to openfsd server

### Result:
swift cannot connect with openfsd; error message: Vatsim auth token endpoint: User not found (see screenshot)
![swift_error](https://github.com/user-attachments/assets/51dbd30d-a415-451b-b8a3-d560386ac6f0)

### Questions:
- can I use my own user database (no vatsim users) with openfsd yet?
- what settings do I need to use in swift to make openfsd work with my own user database?

**Comment by renorris** [comment]
Hi Chris,

Which user credentials are you using to connect? You mentioned "no vatsim users." You must log in with a user account. 

If it does not already exist, the server executable will automatically create a SQLite `.db` file on startup (located at the path set in the `DATABASE_FILE` environment variable.)

On first startup, check your stdout for a message that looks like this:
```
Added user: Default Administrator    CID: 100000    Password: a83a4d5251495422    Rating: Administrator
```
Use this to log into FSD directly and to access the web interface where you can add more users.

If this doesn't show up, delete any existing `.db` file, and try again.

**Comment by renorris** [comment]
Chris,

To follow up: you will need to point Swift to _openfsd's_ "fsd-jwt" authentication server, as it's most likely trying to talk to vatsim's auth servers. I suspect the address may be hard-coded in Swift. Check if there is a way to change this auth server URL. You may be able to recompile swift with the modified URL. See [here](https://github.com/swift-project/pilotclient/blob/019c7a8b276671f0c2d3a2fef8510b2543ffe370/resources/share/shared/bootstrap/bootstrap.json#L48).

I apologize for the confusion. This project is experimental and was not designed to be used in any sort of prod-esque fashion.

Good luck,

Reese

**Comment by Reisen-Wandern-Tauchen** [comment]
Hey Reese,

many thanks for your fast response! That's highly appreciated.
I was able to log into the servers webpage and create my users. But as I'm using a custom user list, I need swift to challenge the servers user database. So I guess your second reply is what I need to dive into more deeply.
Thanks for the hint. I will take my time to investigate.
Feel free to close this issue as the issue seems not related with openFSD but I need to challenge the swift client.

And I highly appreciate the efforts you put into this. Even if experimental, it will help me with my project quite a lot if I can get my users to log in to the custom server.
Currently we are using the very old original FSD server that is lacking the fast packets which is causing various synchronisation problems on our community flights.
So thanks a lot for all the work and time you put into this so far.
Unfortunately, I haven't done anything else than compiling with go so far, so can't offer any help in the actual programming here...

**Comment by renorris** [comment]
I've pushed a commit that should help you out. Setting the `PLAINTEXT_PASSWORDS` environment variable to `true` disables VATSIM "fsd-jwt" authentication and reverts back to the old plaintext password mode.  A server entry for openfsd in the swift client should now work using the following settings:

1. In the Settings > Servers  menu: Make a new server entry for openfsd. For the Eco./Type: field, select `FSD (Private)` for the Eco and `FSD [VATSIM]` for the type.
2. Within that server entry in the FSD specific settings (the FSD tab), it is important to enable all of the flags (send and receive to TRUE):
- "Parts"
- "Gnd. flag"
- "Fast pos" 
- and especially "Send visual pos."

I've just tested this using my own simulator/swift client and it seems to work. Let me know if you have any issues.

**Comment by Reisen-Wandern-Tauchen** [comment]
You're amazing!
Thanks a lot for that commit! I will try it in the next days. Unfortunately, I didn't manage today.
I will let you know if it works. But as you already tested it, I suppose so 😉

**Comment by Reisen-Wandern-Tauchen** [comment]
Allright, one big step forward! :)
I'm able to connect with the server now. Thanks for the additional option and the fix! 🥳

Only one thing: I keep receiving that message:
![image](https://github.com/user-attachments/assets/e431bbd0-c727-4da7-a9dd-3871e24206e3)
Any idea?
I'm using FlightGear as my simulator for testing with swift version 0.14.142

**Comment by Reisen-Wandern-Tauchen** [comment]
Yeah! It worked (after I removed my local git repository, cloned and built the executable again. Thank you so much! 🥳
No I can take the next steps in testing.
And I think we can close this issue.
