### ISSUE TITLE
MySQL connection refused using "mysql_native_password"

### ISSUE THREAD

**Issue by Reisen-Wandern-Tauchen** [renorris/openfsd#5]
Hi,

after some personal issues, I finally managed to do some testing.
Unfortunately, I'm running into an issue with the connection to my MariaDB-Server running on the same machine as openFSD.
Connection to the database server is refused due to an issue with the user authentication method:
```
[mysql] 2024/11/02 11:59:54 connector.go:146: could not use requested auth plugin 'mysql_native_password': this user requires mysql native password authentication
2024/11/02 11:59:54 this user requires mysql native password authentication

```

Command line to run openFSD:
```
GOMAXPROCS=1 FSD_ADDR=0.0.0.0:6810 HTTP_ADDR=0.0.0.0:9086 DOMAIN_NAME=lawa-network.eu MYSQL_USER=dbUsername MYSQL_PASS=dbPassword MYSQL_NET=tcp MYSQL_ADDR=127.0.0.1:3306 MYSQL_DBNAME=dbname ./openfsd
```

Questions:
- What would the expected user authentication method be?
- can the 'mysql_native_password' method be implemented to openFSD?

**Comment by renorris** [comment]
Hey Chris, thanks for the report! I'll check this out sometime this weekend when I have access to a computer.

**Comment by renorris** [comment]
I was able to replicate your problem and pushed a hotfix to the main branch. mysql_native_password should be supported by default.

**Comment by Reisen-Wandern-Tauchen** [comment]
Hey Reese,

thanks so much for the lightning-fast hotfix. It's working like a charm! ❤️

So I think we can close this issue.
